-- Evita duplicados exactos (ignorando mayúsculas) y permite ON CONFLICT en el seed.
CREATE UNIQUE INDEX IF NOT EXISTS ejercicios_catalogo_nombre_unq
  ON ejercicios_catalogo (lower(nombre));

INSERT INTO ejercicios_catalogo (nombre) VALUES
  ('Sentadilla'),
  ('Sentadilla Smith'),
  ('Sentadilla Búlgara'),
  ('Sentadilla Sumo'),
  ('Sentadilla Hack'),
  ('Prensa'),
  ('Peso Muerto'),
  ('Peso Muerto Rumano'),
  ('Peso Muerto Sumo'),
  ('Peso Muerto a una Pierna'),
  ('Zancadas'),
  ('Zancadas con Mancuernas'),
  ('Extensión de Cuádriceps'),
  ('Curl Femoral Sentado'),
  ('Curl Femoral Acostado'),
  ('Curl Femoral de Pie'),
  ('Elevación de Talones (Gemelos)'),
  ('Gemelos Sentado'),
  ('Hip Thrust'),
  ('Puente de Glúteo'),
  ('Abducción de Cadera'),
  ('Aducción de Cadera'),
  ('Dominadas'),
  ('Dominadas Asistidas'),
  ('Remo con Barra'),
  ('Remo con Mancuerna'),
  ('Remo en Polea'),
  ('Remo en Máquina'),
  ('Jalón al Pecho'),
  ('Jalón Tras Nuca'),
  ('Pull Over'),
  ('Remo T'),
  ('Hiperextensiones'),
  ('Press de Banca'),
  ('Press de Banca Inclinado'),
  ('Press de Banca Declinado'),
  ('Press con Mancuernas'),
  ('Press Inclinado con Mancuernas'),
  ('Aperturas con Mancuernas'),
  ('Aperturas en Polea'),
  ('Fondos en Paralelas'),
  ('Cruce de Poleas'),
  ('Press en Máquina'),
  ('Press de Banca Multipower'),
  ('Press Militar'),
  ('Press de Hombro con Mancuernas'),
  ('Elevaciones Laterales'),
  ('Elevaciones Frontales'),
  ('Pájaros (Deltoide Posterior)'),
  ('Face Pull'),
  ('Encogimientos (Trapecio)'),
  ('Press Arnold'),
  ('Curl de Bíceps con Barra'),
  ('Curl de Bíceps con Mancuernas'),
  ('Curl Martillo'),
  ('Curl en Banco Scott'),
  ('Curl en Polea'),
  ('Extensión de Tríceps en Polea'),
  ('Press Francés'),
  ('Fondos de Tríceps'),
  ('Patada de Tríceps'),
  ('Press Cerrado de Banca'),
  ('Plancha'),
  ('Plancha Lateral'),
  ('Crunch'),
  ('Crunch en Polea'),
  ('Elevación de Piernas'),
  ('Rueda Abdominal'),
  ('Russian Twist'),
  ('Abdominales en V'),
  ('Cinta'),
  ('Bicicleta'),
  ('Remo (Cardio)'),
  ('Elíptica'),
  ('Burpees'),
  ('Saltos al Cajón'),
  ('Kettlebell Swing'),
  ('Battle Rope'),
  ('Escaladora')
ON CONFLICT (lower(nombre)) DO NOTHING;
